[package]
name = "nakama-derive"
version = "3.0.0"
authors = ["John Wells <john@attackgoat.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "1.0", features = ["full"] }
